### ISSUE TITLE
Failed to get mobile number because of 'null' 

### ISSUE THREAD

**Issue by chrystoffer** [amorenew/Flutter-Mobile-Number-Plugin#10]
I'm trying to use it on my device, I did exactly the same as the example, but the error doesn't tell me why I didn't return the number.

`Failed to get mobile number because of 'null' `

E/flutter ( 3810): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s)
E/flutter ( 3810): #0      _StringBase.+ (dart:core-patch/string_patch.dart:262:57)
E/flutter ( 3810): #1      MobileNumber.mobileNumber (package:mobile_number/mobile_number.dart:47:45)
E/flutter ( 3810): <asynchronous suspension>
E/flutter ( 3810): #2      _MyAppState.initMobileNumberState (package:teleatendimento_saude_mobile/main.dart:40:41)
E/flutter ( 3810): <asynchronous suspension>
E/flutter ( 3810): #3      _MyAppState.initState (package:teleatendimento_saude_mobile/main.dart:28:5)
E/flutter ( 3810): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
E/flutter ( 3810): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
E/flutter ( 3810): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
E/flutter ( 3810): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
E/flutter ( 3810): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
E/flutter ( 3810): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
E/flutter ( 3810): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
E/flutter ( 3810): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
E/flutter ( 3810): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
E/flutter ( 3810): #13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
E/flutter ( 3810): #14     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
E/flutter ( 3810): #15     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 3810): #16     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 3810): #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 3810): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 3810): #19     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 3810): #20     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 3810): #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 3810): #22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 3810): #23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 3810): #24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 3810): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

does anyone know why?

**Comment by amreniouinnovent** [comment]
@chrystoffer Could you show me your android manifest.xml and MainActivity.java 
And do you request permission before calling it?

**Comment by chrystoffer** [comment]
> @chrystoffer Could you show me your android manifest.xml and MainActivity.java
> And do you request permission before calling it?

I added a print to see what was returning
`[{"carrierName":"TIM","displayName":"TIM","slotIndex":0,"countryIso":"br","countryPhonePrefix":"55"}]`
mobile_number.dart
`static Future<String> get mobileNumber async {
    final String simCardsJson = await _channel.invokeMethod('getMobileNumber');
    if (simCardsJson.isEmpty) {
      return '';
    }
    print('simCardsJson $simCardsJson');
    List<SimCard> simCards = SimCard.parseSimCards(simCardsJson);
    if (simCards != null && simCards.isNotEmpty) {
      return simCards[0].countryPhonePrefix + simCards[0].number;
    } else {
      return '';
    }
  }`

manifest.xml

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Teleatendimento Saúde"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>

MainActivity.java
package br.inf.ids.teleatendimentosaude;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}

yes, permission was requested

**Comment by amorenew** [comment]
@chrystoffer
1- What is your **Android version** number you are testing on?
I suspect this line is return null 
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/7cc3d20a3c864f467ad8a8c9ddd829829ad0f0bc/android/src/main/java/com/amorenew/mobile_number/SimCard.java#L48

2-Could you try on the same device a play store app to check if it returns phone number?
https://play.google.com/store/apps/details?id=com.inspair.mysimmanagerinfo&hl=en_US
or
https://play.google.com/store/apps/details?id=com.steffen_b.multisimselector

If native app returns the phone number then I have an issue otherwise we could use this feature https://github.com/amorenew/Flutter-Mobile-Number-Plugin/issues/9

**Comment by chrystoffer** [comment]
> @chrystoffer
> 1- What is your **Android version** number you are testing on?
> I suspect this line is return null
> https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/7cc3d20a3c864f467ad8a8c9ddd829829ad0f0bc/android/src/main/java/com/amorenew/mobile_number/SimCard.java#L48
> 
> 2-Could you try on the same device a play store app to check if it returns phone number?
> https://play.google.com/store/apps/details?id=com.inspair.mysimmanagerinfo&hl=en_US
> or
> https://play.google.com/store/apps/details?id=com.steffen_b.multisimselector
> 
> If native app returns the phone number then I have an issue otherwise we could use this feature #9

Thanks for the answer. I downloaded both applications but in none of them my phone number appears :(

**Comment by amreniouinnovent** [comment]
@chrystoffer Your sim card not allow getting the mobile number
More info:
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/issues/3
https://stackoverflow.com/questions/10695601/msisdn-is-it-a-sim-card-data-why-all-the-provided-function-from-blackberry-a

In this case, you may support me in the new feature
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/issues/9

I will keep this issue open as I need to add a proper error message

**Comment by amorenew** [comment]
I handled the exception now it will return empty or null
