### ISSUE TITLE
<Request> When Will the IOS be supported ? 

### ISSUE THREAD

**Issue by ctkqiang** [amorenew/Flutter-Mobile-Number-Plugin#12]

**Comment by amreniouinnovent** [comment]
@johnmelodyme ios don't allow fetching the phone number

**Comment by ctkqiang** [comment]
> @johnmelodyme ios don't allow fetching the phone number

Ok then Thanks tho. They [ apple ] Make jobs more difficult.

**Comment by amreniouinnovent** [comment]
@johnmelodyme but I will try to add a popup dialog for ios to enter phone number when I get enough time

**Comment by ctkqiang** [comment]
> @johnmelodyme but I will try to add a popup dialog for ios to enter phone number when I get enough time

thanks :)
