### ISSUE TITLE
MainActiviry in Kotlin

### ISSUE THREAD

**Issue by dwikresno** [amorenew/Flutter-Mobile-Number-Plugin#17]
MobileNumberPlugin.registerWith(registrarFor("com.amorenew.mobile_number.MobileNumberPlugin()"));

how i can white this java code in kotlin

**Comment by amorenew** [comment]
@dwikresno Just use the auto converter
MobileNumberPlugin.registerWith(registrarFor("com.amorenew.mobile_number.MobileNumberPlugin()"))

**Comment by amorenew** [comment]
@dwikresno Check convert from java button on top
https://try.kotlinlang.org/
