### ISSUE TITLE
requestPhonePermission infinite loop

### ISSUE THREAD

**Issue by fasunna** [amorenew/Flutter-Mobile-Number-Plugin#18]
Greetings, 

I found some wierd behaviour when request access for the phone number. If the user has not already provided its answear, the requestPhonePermission popup menu appears as expected. But once the user has denied the phone access, the requestPhonePermission never popup, hanging the code in its Future. I had to put a timeout in requestPhonePermission to be able to passthrough it.

My code:
```dart
    var phoneNumber;
    if (Modular.get<Environment>().build != EnvironmentsType.production && Platform.isAndroid) {
      try {
        if (!(await MobileNumber.hasPhonePermission)) {
          await MobileNumber.requestPhonePermission.timeout(Duration(milliseconds: 1500));
        }
        if (await MobileNumber.hasPhonePermission) {
          phoneNumber = await MobileNumber.mobileNumber;
        }
      } catch (e) {
        print("It was not possible to fetch phone number, $e");
      }
    }
```

My flutter doctor:
```sh
 flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4
    • Framework revision 1aafb3a8b9 (8 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

```

**Comment by amorenew** [comment]
Not sure what is the issue here, but I would suggest using permission hander library in this case

**Comment by krsteve** [comment]
I'm having the exact same issue here. I would love if the following were possible.

* hasPhonePermission to be in 3 states: true, false, and a nullish one (i.e., user has not chosen allow or deny).
* requestPhonePermission clearly ends when hasPhonePermission is in the false state. (Codes following this will not execute when the permission is false.)

**Comment by amorenew** [comment]
@krsteve I can't do it nowadays because I am very busy if you can refactor the code to support that then it is ok

**Comment by OE-Ahmed** [comment]
HELLO @krsteve @amorenew @fabricio-godoi, Any update on this please update anyone I am finding the same solution.

**Comment by fasunna** [comment]
@OE-Ahmed the project I was working on was discontinued, so I no longer have access to it. I think that @amorenew suggestion could work, since [permission_handler](https://pub.dev/packages/permission_handler) has a better implementation of device general permissions. A simple example would be:

```dart
var status = await Permission.phone.status;
if (!status.isGranted) {
  status = await Permission.phone.request();
}

if (!status.isGranted) {
  // return or throw some error
}

return await MobileNumber.mobileNumber;

```

@amorenew if you have any time, I would suggest updating the README.md with this info, or just use permission_handler instead of your own implementation. What do you think about it?

**Comment by amorenew** [comment]
@fabricio-godoi Thanks for the suggestion, I updated the readme
