### ISSUE TITLE
mobileNumber formatting, returned value is merged with country code like 36+36301234567

### ISSUE THREAD

**Issue by giorgio79** [amorenew/Flutter-Mobile-Number-Plugin#21]
Hello,

I am just playing with this package, and in my case, it is returning the number like so

36+36301234567

36 in my case is country code. Could the package separate the number, so we get:
MobileNumber.countryCode=  36;
MobileNumber.phoneNumber = 301234567

**Comment by amorenew** [comment]
@giorgio79 hello,
check `getSimCards`
You will be able to know the country code by `countryPhonePrefix`
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/master/lib/sim_card.dart
