### ISSUE TITLE
Integrate with intl_phone_number_input

### ISSUE THREAD

**Issue by giorgio79** [amorenew/Flutter-Mobile-Number-Plugin#22]
Would be nice if the package would supply a format that we can feed into 
https://pub.dev/packages/intl_phone_number_input

**Comment by amorenew** [comment]
@giorgio79 You could see the data that I can only fetch out of the native Android code here
No extra data exist on Android native
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/master/lib/sim_card.dart
