### ISSUE TITLE
SIM card number is not showing

### ISSUE THREAD

**Issue by ezatechbd** [amorenew/Flutter-Mobile-Number-Plugin#23]
![simInfo](https://user-images.githubusercontent.com/85380844/124418619-b5761f80-dd7d-11eb-81fa-3c1ac85a0018.png)

**Comment by Chemeindefer** [comment]
Any solution?

**Comment by amorenew** [comment]
some sim cards have a pre-registered number on them which allow the hardware to read it and some cards don't have this data on them.
You could try this app to see what is pre-registered on your sim card
https://play.google.com/store/apps/details?id=me.harrygonzalez.simcardinfo
