### ISSUE TITLE
Failed with Samsung mobiles

### ISSUE THREAD

**Issue by Joseph-Nathan** [amorenew/Flutter-Mobile-Number-Plugin#24]
Samsung A21 s
Samsung A71

**Comment by kalkotekedar** [comment]
On samsung device I noticed that Only one sim card is showing not showing the other sim card.

**Comment by koukibadr** [comment]
Hello I tested it on Samsung A12 but it's not showing any phone number

**Comment by josh-atoms** [comment]
Initially, it worked but now, I do get this error when I use in my Redmi "No phone number on sim card#2"

**Comment by amorenew** [comment]
@JAtoms It is not an error, some sim cards don't have the number pre-registered on them.
