### ISSUE TITLE
Failed to fetch mobile number

### ISSUE THREAD

**Issue by sharmaAshish-dev** [amorenew/Flutter-Mobile-Number-Plugin#25]
unable to fetch mobile number but the library is able to get all other details like Carrier name, country number, display name, etc

**Comment by gideonoyekale** [comment]
I have same issue. Any solutions yet?

**Comment by amorenew** [comment]
@gideonoyekale @sharmaAshish-dev 
only if the number is pre-regisrered on the sim card it will fetch it
you can try by any sim card info app on playstore

**Comment by gideonoyekale** [comment]
> @gideonoyekale @sharmaAshish-dev only if the number is pre-regisrered on the sim card it will fetch it you can try by any sim card info app on playstore

You are right. I checked with an app on playstore. Thanks.
