### ISSUE TITLE
Issue get mobile number

### ISSUE THREAD

**Issue by Shrikantmurya** [amorenew/Flutter-Mobile-Number-Plugin#27]
I using package  mobile_number: ^1.0.4 and issue to get mobile number.
**this file not found in fluttetr project MainActivity.java.** 
how to add this code
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MobileNumberPlugin.registerWith(registrarFor("com.amorenew.mobile_number.MobileNumberPlugin()"));
    }

**Comment by amorenew** [comment]
Looks like you don’t need it for new Flutter versions
