### ISSUE TITLE
Can't get mobile phone number

### ISSUE THREAD

**Issue by caiopardal** [amorenew/Flutter-Mobile-Number-Plugin#3]
I'm trying to use the lib, but it isn't returning mobile phone number, just an empty string. Can you help me out?

**Comment by amorenew** [comment]
@caiopardal Not every sim card has a registered number on it.

**Comment by wbdsnx** [comment]
> @caiopardal Not every sim card has a registered number on it.
I have register my sim,but I con't get phoneNumber. And I connot understand what you said.

**Comment by amreniouinnovent** [comment]
@wbdsnx Not every sim card had that feature
https://stackoverflow.com/questions/21497766/getline1number-returns-blank-not-null

**More on MSISDN Feature:**
https://stackoverflow.com/questions/10695601/msisdn-is-it-a-sim-card-data-why-all-the-provided-function-from-blackberry-a

But I think that guy has a good idea, By checking the last send SMS I can get the phone number
I will open this issue until I investigate the SMS workaround solution.
https://stackoverflow.com/questions/6758875/why-cant-the-telephonymanager-get-the-phone-number-from-the-sim

**Comment by amorenew** [comment]
@caiopardal @wbdsnx Could you test the same case with version 0.0.6
