### ISSUE TITLE
i heve 2 sime card in my phone but it is showing only one sim card details

### ISSUE THREAD

**Issue by Kalyanb447-github** [amorenew/Flutter-Mobile-Number-Plugin#30]
i am using Realme GT phone sdk 31

**Comment by amorenew** [comment]
@Kalyanb447-github some sim cards doesn’t register its data on the sim so even if you get an app from playstore it will not read its data

**Comment by Kalyanb447-github** [comment]
I have registered in the same setting that I have to seen with number also
But whenever I am using the package getting one sim card detail
