### ISSUE TITLE
This returns single sim data for dual sim phones

### ISSUE THREAD

**Issue by atulkapoor** [amorenew/Flutter-Mobile-Number-Plugin#31]
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/a0f217b3466b3c5dee18dc40c80cc19e70a00e50/android/src/main/java/com/amorenew/mobile_number/MobileNumberPlugin.java#L200

This should return all list data

**Comment by amorenew** [comment]
@atulkapoor it is single, check the name `getSingleSimCard`

use   `static Future<List<SimCard>>? get getSimCards async`
