### ISSUE TITLE
sim card number not showing 

### ISSUE THREAD

**Issue by Krutika7038878317** [amorenew/Flutter-Mobile-Number-Plugin#32]
in dual sim showing only first slot sim card please give me solution

**Comment by amorenew** [comment]
@Krutika7038878317 is the **2nd** number shows up by this app? or any similar "sim card info" apps?
https://play.google.com/store/apps/details?id=me.harrygonzalez.simcardinfo

**Comment by cogos-aishwarya** [comment]
Facing the same issue as @Krutika7038878317 . Still not seem to be resolved

**Comment by amorenew** [comment]
@cogos-aishwarya try the given app to test.

**Comment by dineshMadvise** [comment]
In dual sim showing only first slot sim card please give me solution. Second sim card num now showing.

**Comment by amorenew** [comment]
I don't know the solution for it 😭

**Comment by PritamJoshi1** [comment]
i am also facing the issue to get sim cards i am using getSimCards property of MobileNumber class but in some cases i get only 1 sim card number in some cases i can't get any sim card number

**Comment by krishnagadekar** [comment]
> in dual sim showing only first slot sim card please give me solution

i also get same issue please tell some solution

**Comment by amorenew** [comment]
it is not avaialable for all sim cards
