### ISSUE TITLE
sim card android 11+ null

### ISSUE THREAD

**Issue by rekan-ismail** [amorenew/Flutter-Mobile-Number-Plugin#34]
![photo_2022-09-12_06-58-57](https://user-images.githubusercontent.com/72127116/189571432-32c2f1c7-d03f-41d9-a558-5c06690a39be.jpg)
 
android 11+ api 30+device get null !

**Comment by amorenew** [comment]
In emulator it return data so it maybe a sim card issue as some sim cards doesn't have a pre-registered phone number on it
