### ISSUE TITLE
sim card number not showing

### ISSUE THREAD

**Issue by ShanuM123** [amorenew/Flutter-Mobile-Number-Plugin#35]
Three Scenarios we faced in this plugin(Android): -
1) Only the first sim is showing on a few devices, - 80% of Device
2) None of the sim is showing on a few devices, - 10% Device
3) Both sim is showing, - a 10% Device

Any Solution?

**Comment by amorenew** [comment]
@ShanuM123 
some sim cards have a pre-registered number on them which allow the hardware to read it and some cards don't have this data on them.
if you run the plugin on the emulator it will always work
so I don't know how to solve these cases
