### ISSUE TITLE
getActiveSubscriptionInfoList() from  SubscriptionManager can be null

### ISSUE THREAD

**Issue by urielvexi** [amorenew/Flutter-Mobile-Number-Plugin#39]
in the next link you can find info about getActiveSubscriptionInfoList() returning null
https://developer.android.com/reference/android/telephony/SubscriptionManager#getActiveSubscriptionInfoList()

error PlatformException(error, Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference at f1.b.i(Unknown Source:15) at f1.b.j(Unknown Source:10) at f1.b.d(Unknown Source:79) at d6.k$a.a(Unknown Source:17) at q5.c.l(Unknown Source:18) at q5.c.m(Unknown Source:20) at q5.c.i(Unknown Source:0) at q5.b.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:907) at android.os.Handler.dispatchMessage(Handler.java:105) at android.os.Looper.loop(Looper.java:216) at android.app.ActivityThread.main(ActivityThread.java:7625) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) )

**Comment by amorenew** [comment]
it is fixed on version 3.0.0
