### ISSUE TITLE
Multiple Phone Numbers reading is not supported

### ISSUE THREAD

**Issue by pratikjain04** [amorenew/Flutter-Mobile-Number-Plugin#4]

**Comment by amorenew** [comment]
@pratikjain04 If sim card has the phone number registered on it then you will be able to get it.
I have 2 sim cards Vodafone and Etisalat but only Vodafone returns the number.
So If I want to get the 2 sim cards I don't have sim cards for test.

**Comment by pratikjain04** [comment]
But the code only receive a single String always. But do we even get multiple phone numbers?

**Comment by amorenew** [comment]
There is a modification required for this feature
I could work on it next week
This is the code for getting line number 
`String line1Number = telephonyManager.getLine1Number();`
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/master/android/src/main/java/com/example/mobile_number/MobileNumberPlugin.java#L81

**Comment by amorenew** [comment]
@pratikjain04 I added multi sim card check version 0.0.6
