### ISSUE TITLE
can't get SIM number

### ISSUE THREAD

**Issue by wepashka** [amorenew/Flutter-Mobile-Number-Plugin#40]
It can't help to get SIM number on android

**Comment by amorenew** [comment]
It is not working for all sim cards

**Comment by wepashka** [comment]
I have check on 4 device on different kinds but it didn't work? Don't you know any alternative solution?

**Comment by amorenew** [comment]
@wepashka it is related to the sim card itself
not every mobile operator pre-registering the sim data on it
you could try on the play store any app like sim card info to check what kind of data is exist on it
