### ISSUE TITLE
Getting only single sim card number 

### ISSUE THREAD

**Issue by rishi-sileo** [amorenew/Flutter-Mobile-Number-Plugin#41]
There are 2 sim in my phone but I am getting only single sim information

**Comment by amorenew** [comment]
@rishi-sileo 
some sim cards have a pre-registered number on them which allow the hardware to read it and some cards don't have this data on them.
You could try this app to see what is pre-registered on your sim card
https://play.google.com/store/apps/details?id=me.harrygonzalez.simcardinfo
