### ISSUE TITLE
Second SIM data is not getting

### ISSUE THREAD

**Issue by sgrchavan01** [amorenew/Flutter-Mobile-Number-Plugin#42]
If there is dual sim card the only first sim card data is showing, not getting second sim card data

**Comment by brijesh-chauhan-ha** [comment]
yes only first sim is showing , even i switched the sim , i am getting only first sim slot data

**Comment by SurajJoshi-Dev** [comment]
yes only one sim get its urgent so please update you're package ASAP!

**Comment by ashishrawatashu** [comment]
Please solve this issue ASAP we are in big trouble . 😖 🤯

**Comment by amorenew** [comment]
try a sim card info on the play store to check what is written on the sim card, not all sim cards has. pre-registered data on it
