### ISSUE TITLE
Not getting sim number on some devices and and on some devices getting only one sim among two

### ISSUE THREAD

**Issue by PritamJoshi1** [amorenew/Flutter-Mobile-Number-Plugin#43]
i am using MobileNumber class and getSimCards static property of this class but on some devices i am getting only 1 sim number from available 2 sim cards and in some cases i get neither sim1 nor sim2

**Comment by amorenew** [comment]
@PritamJoshi1 I don’t no a solution for this case, I use the default Android implementation

**Comment by Zeus9820** [comment]
Yes i am also facing the same issue it always reads the first sim card

**Comment by vikasborage** [comment]
for me  it detect  the both the sims but one of hem display number as null 

carrierName: "Vi India — Idea"
countryIso: "in"
countryPhonePrefix:"91"
number:null 
slotIndex:0

**Comment by sandeep-pani** [comment]
Same issue

**Comment by aneeshdevala** [comment]
same issue

**Comment by amorenew** [comment]
it is not available for all sim cards
