### ISSUE TITLE
Error after install mobile_number

### ISSUE THREAD

**Issue by GabrielAispuro** [amorenew/Flutter-Mobile-Number-Plugin#6]
Hi man, I was trying to get the phone number of an Android device and I found this plugin. But after installing it, I couldn't run my app. 
<img width="1010" alt="Captura de Pantalla 2020-05-08 a la(s) 15 11 40" src="https://user-images.githubusercontent.com/15963422/81445349-4af82e00-913e-11ea-9162-e4e1df70dcf5.png">

**Comment by amorenew** [comment]
@GabrielAispuro I will check it?
Is it Flutter 1.17?

**Comment by GabrielAispuro** [comment]
Yes 
<img width="704" alt="Captura de Pantalla 2020-05-08 a la(s) 17 14 54" src="https://user-images.githubusercontent.com/15963422/81453571-7e8f8400-914f-11ea-8acc-d2f4f1d1dc87.png">

**Comment by amorenew** [comment]
@GabrielAispuro I added Plugin V2 style to support Flutter 1.17 but I got null on context So I asked support from flutter's team
https://github.com/flutter/flutter/issues/56739

**Comment by GabrielAispuro** [comment]
> @GabrielAispuro I added Plugin V2 style to support Flutter 1.17 but I got null on context So I asked support from flutter's team
> [flutter/flutter#56739](https://github.com/flutter/flutter/issues/56739)

Got it, and thank you so much!

**Comment by amorenew** [comment]
@GabrielAispuro
I fixed it
 I updated it to **version 1.0.0** and I added permission handler check the updated documentation
https://pub.dev/packages/mobile_number
