### ISSUE TITLE
Could not get mobile number normally

### ISSUE THREAD

**Issue by daigewuwy** [amorenew/Flutter-Mobile-Number-Plugin#7]
**What happened:**

Something wrong occur in android when i try to get mobile number by using mobile_number: 1.0.0.

**stack output**

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#mobile_number(21785): 	at android.telephony.SubscriptionManager.from(SubscriptionManager.java:992)
E/MethodChannel#mobile_number(21785): 	at com.example.mobile_number.MobileNumberPlugin.generateMobileNumber(MobileNumberPlugin.java:183)
E/MethodChannel#mobile_number(21785): 	at com.example.mobile_number.MobileNumberPlugin.getMobileNumber(MobileNumberPlugin.java:170)
E/MethodChannel#mobile_number(21785): 	at com.example.mobile_number.MobileNumberPlugin.onMethodCall(MobileNumberPlugin.java:119)
E/MethodChannel#mobile_number(21785): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#mobile_number(21785): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#mobile_number(21785): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#mobile_number(21785): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#mobile_number(21785): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#mobile_number(21785): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#mobile_number(21785): 	at android.app.ActivityThread.main(ActivityThread.java:7589)
E/MethodChannel#mobile_number(21785): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#mobile_number(21785): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#mobile_number(21785): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
I/flutter (21785): Failed to get mobile number because of 'Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference'

**What have I done:**

My device system version is android 10, i can not get mobile number also when run the example in pub.
I had add the permission declare in AndroidManifest.xml like below:

     <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>

**Comment by amorenew** [comment]
@daigewuwy oh it looks like the issue is related to Android 10
`            final List<SubscriptionInfo> activeSubscriptionInfoList = subscriptionManager.getActiveSubscriptionInfoList();
`
a null exception on subscriptionManager

**Comment by amorenew** [comment]
@daigewuwy I don't have Android 10 only Android 9
But I tried on the emulator and there is no problem
![image](https://user-images.githubusercontent.com/2842459/82380133-096a5b80-9a39-11ea-91fb-f891ff1cce4e.png)

some StackOverflow suggest that I should replace  
SubscriptionManager.from(activity);
by applicationContextgetSystemService
https://stackoverflow.com/questions/52554713/subscriptionmanager-from-deprecated
I will try it on weekend

**Comment by daigewuwy** [comment]
> @daigewuwy我没有Android 10，只有Android 9，
> 但是我在模拟器上尝试过，没有问题
> ![图片](https://user-images.githubusercontent.com/2842459/82380133-096a5b80-9a39-11ea-91fb-f891ff1cce4e.png)
> 
> 一些StackOverflow建议我应该替换
> SubscriptionManager.from（activity）;
> 通过applicationContextgetSystemService
> https://stackoverflow.com/questions/52554713/subscriptionmanager-from-deprecated
> 我将在周末尝试

Thanks for you reply.
I got the same exception when running the example of mobile_number: 0.0.6 and 1.0.0, Whether it's Android 7 or Android 10.
I wonder if I've missed some steps, I will try to solve it follow the stackoverflow link.

**Comment by amorenew** [comment]
@daigewuwy You are welcome
Could you replace 
SubscriptionManager.from
by
  (SubscriptionManager) getSystemService(Context.TELEPHONY_SUBSCRIPTION_SERVICE);
in the native java and tell me if still same error?

**Comment by daigewuwy** [comment]
An error occurred during compilation after i replace the SubscriptionManager.from，the exception details looks like the text below：
```
F:\EnvironmentalScience\Flutter\flutter\.pub-cache\hosted\pub.flutter-io.cn\mobile_number-1.0.0\android\src\main\java\com\example\mobile_number\MobileNumberPlugin.java:183: ����: �Ҳ�������
            subscriptionManager = (SubscriptionManager)getSystemService(Context.TELEPHONY_SUBSCRIPTION_SERVICE);
```
I'm not good at Java， Do I need to import any dependencies

**Comment by daigewuwy** [comment]
> @daigewuwy欢迎
> 您，您可以 用 （SubscriptionManager）getSystemService（Context.TELEPHONY_SUBSCRIPTION_SERVICE）替换
> SubscriptionManager.from 吗？ 在本机的Java中，告诉我是否仍然存在相同的错误？

Hello, i replaced the origin method call, and i got a empty string of mobile.The final method call like below:
`subscriptionManager = (SubscriptionManager)this.applicationContext.getSystemService(Context.TELEPHONY_SUBSCRIPTION_SERVICE);`

**Comment by amorenew** [comment]
@daigewuwy Could you try any native app so I know if it works fine with you
https://play.google.com/store/apps/details?id=com.inspair.mysimmanagerinfo&hl=en_US
or
https://play.google.com/store/apps/details?id=com.steffen_b.multisimselector

**Comment by daigewuwy** [comment]
> @daigewuwy您可以尝试使用任何本机应用程序吗，所以我知道它是否可以正常使用
> [https://play.google.com/store/apps/details?id=com.inspair.mysimmanagerinfo&hl=zh_CN](https://play.google.com/store/apps/details?id=com.inspair.mysimmanagerinfo&hl=en_US)
> 或
> [https://play.google .com / store / apps / details？id = com.steffen_b.multisimselector](https://play.google.com/store/apps/details?id=com.steffen_b.multisimselector)

The plugin works for me now.The new version of the system does not allow app to access device information by default.My device is XiaoMi 8, system version is MIUI 12.
Finally, thank you for your patient guidance, it's noticeable that my english is poor.

**Comment by amorenew** [comment]
@daigewuwy No problem I am not an English speaker.
I don't get it did you change your mobile settings or it is just working with no changes?
Do you do similar settings or how it got fixed?
https://webcazine.com/12744/how-to-fix-my-phone-number-showing-unknown-on-xiaomi-phone-running-miui-v5/

**Comment by wiradikusuma** [comment]
Adding my 2 cents, this library also doesn't work with similar error in Pixel 2 (Android 10).

**Comment by daigewuwy** [comment]
> @daigewuwy No problem I am not an English speaker.
> I don't get it did you change your mobile settings or it is just working with no changes?
> Do you do similar settings or how it got fixed?
> https://webcazine.com/12744/how-to-fix-my-phone-number-showing-unknown-on-xiaomi-phone-running-miui-v5/

Yes, i changed some setting about permission in my device system.MIUI is a special system, it does not allow app to read device info by default in the new version.The plugin works for me now.

**Comment by amorenew** [comment]
@daigewuwy  @wiradikusuma 
Could you try the new version?
mobile_number **1.0.1**

**Comment by daigewuwy** [comment]
@amorenew I can get the mobile number normally when running the example by using mobile_ number:1.0.0 after I grant permission, . But with mobile_ number:1.0.1, even i give the permission, I still can't get the mobile number. The key error message is as follows:
E/MethodChannel#mobile_number(19430): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#mobile_number(19430): 	at com.example.mobile_number.MobileNumberPlugin.getSubscriptions(MobileNumberPlugin.java:212)

**Comment by amorenew** [comment]
@daigewuwy do your MainActivity extend of FlutterActivity?

**Comment by amorenew** [comment]
@daigewuwy I think your MainActivity is extended of `import io.flutter.app.FlutterActivity;` not `import io.flutter.embedding.android.FlutterActivity;`

I have updated the **readme** for old Flutter Activity
you could use version 1.0.2
and add in your MainActivity.java
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MobileNumberPlugin.registerWith(registrarFor("com.amorenew.mobile_number.MobileNumberPlugin()"));
    }
```
