### ISSUE TITLE
shouldShowRequestPermissionRationale() on a null object reference

### ISSUE THREAD

**Issue by wiradikusuma** [amorenew/Flutter-Mobile-Number-Plugin#8]
Using Google Pixel 2 (Android 10), this error is thrown when `MobileNumber.requestPhonePermission` is called:

	[+17486 ms] E/MethodChannel#mobile_number(10782): Failed to handle method call
	[        ] E/MethodChannel#mobile_number(10782): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Activity.shouldShowRequestPermissionRationale(java.lang.String)' on a null object reference
	[        ] E/MethodChannel#mobile_number(10782): 	at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:549)
	[        ] E/MethodChannel#mobile_number(10782): 	at com.example.mobile_number.MobileNumberPlugin.requestPhonePermission(MobileNumberPlugin.java:155)
	[        ] E/MethodChannel#mobile_number(10782): 	at com.example.mobile_number.MobileNumberPlugin.onMethodCall(MobileNumberPlugin.java:125)
	[        ] E/MethodChannel#mobile_number(10782): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
	[        ] E/MethodChannel#mobile_number(10782): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	[        ] E/MethodChannel#mobile_number(10782): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
	[        ] E/MethodChannel#mobile_number(10782): 	at android.os.MessageQueue.nativePollOnce(Native Method)
	[        ] E/MethodChannel#mobile_number(10782): 	at android.os.MessageQueue.next(MessageQueue.java:336)
	[        ] E/MethodChannel#mobile_number(10782): 	at android.os.Looper.loop(Looper.java:174)
	[        ] E/MethodChannel#mobile_number(10782): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
	[        ] E/MethodChannel#mobile_number(10782): 	at java.lang.reflect.Method.invoke(Native Method)
	[        ] E/MethodChannel#mobile_number(10782): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	[        ] E/MethodChannel#mobile_number(10782): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
	[ +236 ms] E/flutter (10782): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean android.app.Activity.shouldShowRequestPermissionRationale(java.lang.String)' on a null object reference, null)
	[        ] E/flutter (10782): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
	[        ] E/flutter (10782): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
	[        ] E/flutter (10782): <asynchronous suspension>
	[        ] E/flutter (10782): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
	[        ] E/flutter (10782): #3      MobileNumber.requestPhonePermission (package:mobile_number/mobile_number.dart:35:20)

Permissions in `AndroidManifest.xml`:

    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>

Any ideas?

**Comment by amorenew** [comment]
@wiradikusuma is it existed in the new version mobile_number 1.0.1?

**Comment by wiradikusuma** [comment]
Yes, still the same problem in my Pixel 2.

When I tried in ASUS Z008 (Android 5), exception is thrown even at `MobileNumber.hasPhonePermission`:

	[+24384 ms] E/MethodChannel#mobile_number( 5857): Failed to handle method call
	[        ] E/MethodChannel#mobile_number( 5857): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
	[        ] E/MethodChannel#mobile_number( 5857): 	at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:535)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.example.mobile_number.MobileNumberPlugin.getSingleSimCard(MobileNumberPlugin.java:199)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.example.mobile_number.MobileNumberPlugin.generateMobileNumber(MobileNumberPlugin.java:184)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.example.mobile_number.MobileNumberPlugin.getMobileNumber(MobileNumberPlugin.java:169)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.example.mobile_number.MobileNumberPlugin.onMethodCall(MobileNumberPlugin.java:119)
	[        ] E/MethodChannel#mobile_number( 5857): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
	[        ] E/MethodChannel#mobile_number( 5857): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	[        ] E/MethodChannel#mobile_number( 5857): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
	[        ] E/MethodChannel#mobile_number( 5857): 	at android.os.MessageQueue.nativePollOnce(Native Method)
	[        ] E/MethodChannel#mobile_number( 5857): 	at android.os.MessageQueue.next(MessageQueue.java:143)
	[        ] E/MethodChannel#mobile_number( 5857): 	at android.os.Looper.loop(Looper.java:122)
	[        ] E/MethodChannel#mobile_number( 5857): 	at android.app.ActivityThread.main(ActivityThread.java:5264)
	[        ] E/MethodChannel#mobile_number( 5857): 	at java.lang.reflect.Method.invoke(Native Method)
	[        ] E/MethodChannel#mobile_number( 5857): 	at java.lang.reflect.Method.invoke(Method.java:372)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
	[        ] E/MethodChannel#mobile_number( 5857): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
	[ +627 ms] I/flutter ( 5857): Unable to get mobile number: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference

**Comment by wiradikusuma** [comment]
Same error in Oppo X9009 (Android 5) when calling `MobileNumber.hasPhonePermission`.

**Comment by wiradikusuma** [comment]
Just tried it in BlackBerry KeyOne (Android 7), also doesn't work. No error shown, but that's probably my device issue :)

**Comment by amorenew** [comment]
@wiradikusuma I will check it on weekend

**Comment by amorenew** [comment]
@wiradikusuma see this line in example dart
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/f51462953c5c3e5e0cde12cf6a6f0f911a7785bd/example/lib/main.dart#L28
Could you try 2 experiments?
Experiment 1:
change it to
```
if (mounted) {
    initMobileNumberState();
};

```
Experiment 2:
Add to a button `onPress` function

And tell me if it works so I could add it in docs

Thanks

**Comment by wiradikusuma** [comment]
Apparently it's not this library's fault. 

I compared `MainActivity` from your `example` and mine, apparently Flutter changed something (https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration). Basically I have to change my `MainActivity` to be like this:

    import io.flutter.embedding.android.FlutterActivity;

    public class MainActivity extends FlutterActivity {
    }

I'm not sure if this is something that this library can control, but I think it's useful to mention this somewhere in the README (or just point to my comment).

Now it works for all of the devices I mentioned earlier. Thank you!

**Comment by amorenew** [comment]
@wiradikusuma You are right.
I wonder should I update the plugin documentation? or there is any solution to support old Flutter implementation?
I have old support Plugin V1 in this line but it is not working
https://github.com/amorenew/Flutter-Mobile-Number-Plugin/blob/f51462953c5c3e5e0cde12cf6a6f0f911a7785bd/android/src/main/java/com/example/mobile_number/MobileNumberPlugin.java#L54

**Comment by wiradikusuma** [comment]
I think you don't need to support old Flutter implemention, as the fix is easy (like how I did it) :)

**Comment by amorenew** [comment]
@wiradikusuma I added to readme the following
```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MobileNumberPlugin.registerWith(registrarFor("com.amorenew.mobile_number.MobileNumberPlugin()"));
    }
```
Please use 1.0.2 I have supported old flutter plugin V1
if it works fine you could the issue
